# Generated by Django 4.2 on 2025-01-29 06:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("shop", models.CharField(max_length=25)),
                ("price", models.FloatField()),
                ("sku", models.CharField(max_length=5)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=50)),
                ("discount", models.IntegerField()),
                ("category", models.CharField(max_length=25)),
                ("stock", models.IntegerField()),
                ("is_available", models.BooleanField()),
                ("picture", models.URLField()),
            ],
        ),
    ]
