# Generated by Django 4.2 on 2025-01-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openShop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_delete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(),
        ),
    ]
